steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - create
      - '--name'
      - mybuilder
    id: create-builder
  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - use
      - mybuilder
    id: select-builder
  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - build
      - '-t'
      - $_IMAGE_NAME:latest
      - '-t'
      - $_IMAGE_NAME:$TAG_NAME
      - '-f'
      - ./Dockerfile
      - '--push'
      - '--progress=plain'
      - .
    id: Build
  # DEPLOY NEW IMAGE TO STAGING ================================================
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args:
  #     [
  #       'set',
  #       'image',
  #       'deployment',
  #       'lightning-demo',
  #       'lightning-demo=$_IMAGE_NAME:$TAG_NAME',
  #     ]
  #   env:
  #     - 'CLOUDSDK_COMPUTE_ZONE=us-east4-c'
  #     - 'CLOUDSDK_CONTAINER_CLUSTER=prod-cluster'
# Push images to Google Container Registry with tags ===========================
# images: ['$_IMAGE_TAG:$TAG_NAME', '$_IMAGE_TAG:latest']
substitutions:
  _CACHE_NAME: '${_IMAGE_NAME}-build-cache'
options:
  # machineType: 'N1_HIGHCPU_8'
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - LOCAL_BUILD=true
tags:
  - gcp-cloud-build-deploy
timeout: 3600s