name: Build docs and deploy to github pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: 25.2
          elixir-version: '1.14.2'
      - run: mix deps.get
      - run: mix docs

      - name: Generate docs 🔧
        run: |
          mix deps.get
          mix docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: doc # The folder the action should deploy.
