name: Build docs and deploy to github pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup elixir & erlang
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.2"
          elixir-version: "1.13.4"

      - name: Generate docs 🔧
        run: |
          mix deps.get
          mix docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
